// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTune(arg1:number):Promise<string>;

export function GetListenAddr():Promise<string>;

export function GetMode():Promise<string>;

export function GetSessionsDir():Promise<string>;

export function ImportTunes(arg1:Array<main.CarTune>):Promise<number|string>;

export function ListSessions():Promise<Array<string>>;

export function ListTunes(arg1:string):Promise<Array<main.CarTune>>;

export function OpenSessionsDir():Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<string>;

export function ReplayPause():Promise<void>;

export function ReplayResume():Promise<void>;

export function ReplaySeek(arg1:number):Promise<void>;

export function SaveListenAddr(arg1:string):Promise<string>;

export function SaveTune(arg1:main.CarTune):Promise<main.CarTune|string>;

export function StartRecord(arg1:string):Promise<string>;

export function StartReplay(arg1:string,arg2:boolean):Promise<string>;

export function StopSession():Promise<void>;
