// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTune(arg1) {
  return window['go']['main']['App']['DeleteTune'](arg1);
}

export function GetListenAddr() {
  return window['go']['main']['App']['GetListenAddr']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function GetSessionsDir() {
  return window['go']['main']['App']['GetSessionsDir']();
}

export function ImportTunes(arg1) {
  return window['go']['main']['App']['ImportTunes'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTunes(arg1) {
  return window['go']['main']['App']['ListTunes'](arg1);
}

export function OpenSessionsDir() {
  return window['go']['main']['App']['OpenSessionsDir']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ReplayPause() {
  return window['go']['main']['App']['ReplayPause']();
}

export function ReplayResume() {
  return window['go']['main']['App']['ReplayResume']();
}

export function ReplaySeek(arg1) {
  return window['go']['main']['App']['ReplaySeek'](arg1);
}

export function SaveListenAddr(arg1) {
  return window['go']['main']['App']['SaveListenAddr'](arg1);
}

export function SaveTune(arg1) {
  return window['go']['main']['App']['SaveTune'](arg1);
}

export function StartRecord(arg1) {
  return window['go']['main']['App']['StartRecord'](arg1);
}

export function StartReplay(arg1, arg2) {
  return window['go']['main']['App']['StartReplay'](arg1, arg2);
}

export function StopSession() {
  return window['go']['main']['App']['StopSession']();
}
